version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install PDM
          command: pip install pdm
      - run:
          name: Install dependencies with PDM
          command: pdm install
      - run:
          name: Run tests
          command: pdm run pytest